USA = {
    "AL": [None, ["MS", "TN", "FL", "GA"]],
    "AK": [None, []],
    "AZ": [None, ["CA", "NV", "UT", "NM"]],
    "AR": [None, ["MO", "OK", "LA", "MS", "TN", "TX"]],
    "CA": [None, ["OR", "NV", "AZ"]],
    "CO": [None, ["WY", "UT", "NM", "OK", "KS", "NE"]],
    "CT": [None, ["NY", "RI", "MA"]],
    "DE": [None, ["MD", "PA", "NJ"]],
    "FL": [None, ["AL", "GA"]],
    "GA": [None, ["FL", "AL", "SC", "NC", "TN"]],
    "HI": [None, []],
    "ID": [None, ["WA", "OR", "NV", "UT", "MT", "WY"]],
    "IL": [None, ["IN", "KY", "MO", "IA", "WI"]],
    "IN": [None, ["IL", "MI", "KY", "OH"]],
    "IA": [None, ["MN", "SD", "NE", "MO", "IL", "WI"]],
    "KS": [None, ["NE", "CO", "OK", "MO"]],
    "KY": [None, ["IL", "MO", "TN", "VA", "WV", "OH", "IN"]],
    "LA": [None, ["AR", "TX", "MS"]],
    "ME": [None, ["NH"]],
    "MD": [None, ["PA", "WV", "VA", "DE"]],
    "MA": [None, ["RI", "CT", "NH", "VT", "NY"]],
    "MI": [None, ["WI", "IN", "OH"]],
    "MN": [None, ["ND", "SD", "IA", "WI"]],
    "MS": [None, ["LA", "AR", "TN", "AL"]],
    "MO": [None, ["IA", "NE", "KS", "OK", "AR", "TN", "KY", "IL"]],
    "MT": [None, ["ID", "WY", "ND", "SD"]],
    "NE": [None, ["SD", "WY", "CO", "KS", "MO", "IA"]],
    "NV": [None, ["CA", "ID", "OR", "AZ", "UT"]],
    "NH": [None, ["ME", "VT", "MA"]],
    "NJ": [None, ["PA", "DE", "NY"]],
    "NM": [None, ["CO", "AZ", "TX", "OK", "KS"]],
    "NY": [None, ["PA", "NJ", "CT", "VT", "MA"]],
    "NC": [None, ["SC", "TN", "VA"]],
    "ND": [None, ["MT", "SD", "MN"]],
    "OH": [None, ["MI", "IN", "KY", "WV", "PA"]],
    "OK": [None, ["KS", "CO", "NM", "TX", "AR", "MO"]],
    "OR": [None, ["WA", "ID", "CA", "NV"]],
    "PA": [None, ["OH", "WV", "MD", "DE", "NJ", "NY"]],
    "RI": [None, ["CT", "MA"]],
    "SC": [None, ["GA", "NC"]],
    "SD": [None, ["ND", "MT", "WY", "NE", "IA", "MN"]],
    "TN": [None, ["MS", "AL", "GA", "NC", "VA", "KY", "MO", "AR"]],
    "TX": [None, ["NM", "OK", "AR", "LA"]],
    "UT": [None, ["ID", "NV", "AZ", "CO", "WY"]],
    "VT": [None, ["MA", "NH", "NY"]],
    "VA": [None, ["WV", "KY", "NC", "MD"]],
    "WA": [None, ["OR", "ID"]],
    "WV": [None, ["OH", "KY", "VA", "MD", "PA"]],
    "WI": [None, ["MN", "IA", "IL", "MI"]],
    "WY": [None, ["MT", "ID", "UT", "CO", "NE", "SD"]]
}

USA_CUT = {
    "AL": [None, ["MS", "TN", "FL", "GA"]],
    "AZ": [None, ["CA", "NV", "UT", "NM"]],
    "AR": [None, ["MO", "OK", "LA", "MS", "TN", "TX"]],
    "CA": [None, ["OR", "NV", "AZ"]],
    "CO": [None, ["WY", "UT", "NM", "OK", "KS", "NE"]],
    "CT": [None, ["NY", "RI", "MA"]],
    "DE": [None, ["MD", "PA", "NJ"]],
    "FL": [None, ["AL", "GA"]],
    "GA": [None, ["FL", "AL", "SC", "NC", "TN"]],
    "ID": [None, ["WA", "OR", "NV", "UT", "MT", "WY"]],
    "IL": [None, ["IN", "KY", "MO", "IA", "WI"]],
    "IN": [None, ["IL", "MI", "KY", "OH"]],
    "IA": [None, ["MN", "SD", "NE", "MO", "IL", "WI"]],
    "KS": [None, ["NE", "CO", "OK", "MO"]],
    "KY": [None, ["IL", "MO", "TN", "VA", "WV", "OH", "IN"]],
    "LA": [None, ["AR", "TX", "MS"]],
    "ME": [None, ["NH"]],
    "MD": [None, ["PA", "WV", "VA", "DE"]],
    "MA": [None, ["RI", "CT", "NH", "VT", "NY"]],
    "MI": [None, ["WI", "IN", "OH"]],
    "MN": [None, ["ND", "SD", "IA", "WI"]],
    "MS": [None, ["LA", "AR", "TN", "AL"]],
    "MO": [None, ["IA", "NE", "KS", "OK", "AR", "TN", "KY", "IL"]],
    "MT": [None, ["ID", "WY", "ND", "SD"]],
    "NE": [None, ["SD", "WY", "CO", "KS", "MO", "IA"]],
    "NV": [None, ["CA", "ID", "OR", "AZ", "UT"]],
    "NH": [None, ["ME", "VT", "MA"]],
    "NJ": [None, ["PA", "DE", "NY"]],
    "NM": [None, ["CO", "AZ", "TX", "OK", "KS"]],
    "NY": [None, ["PA", "NJ", "CT", "VT", "MA"]],
    "NC": [None, ["SC", "TN", "VA"]],
    "ND": [None, ["MT", "SD", "MN"]],
    "OH": [None, ["MI", "IN", "KY", "WV", "PA"]],
    "OK": [None, ["KS", "CO", "NM", "TX", "AR", "MO"]],
    "OR": [None, ["WA", "ID", "CA", "NV"]],
    "PA": [None, ["OH", "WV", "MD", "DE", "NJ", "NY"]],
    "RI": [None, ["CT", "MA"]],
    "SC": [None, ["GA", "NC"]],
    "SD": [None, ["ND", "MT", "WY", "NE", "IA", "MN"]],
    "TN": [None, ["MS", "AL", "GA", "NC", "VA", "KY", "MO", "AR"]],
    "TX": [None, ["NM", "OK", "AR", "LA"]],
    "UT": [None, ["ID", "NV", "AZ", "CO", "WY"]],
    "VT": [None, ["MA", "NH", "NY"]],
    "VA": [None, ["WV", "KY", "NC", "MD"]],
    "WA": [None, ["OR", "ID"]],
    "WV": [None, ["OH", "KY", "VA", "MD", "PA"]],
    "WI": [None, ["MN", "IA", "IL", "MI"]],
    "WY": [None, ["MT", "ID", "UT", "CO", "NE", "SD"]]
}

TEST_CUT = {
    "A": [None, ['B', 'C', 'D', 'E', 'F']],
    "B": [None, ['A', 'C', 'F', 'G']],
    "C": [None, ['A', 'B', 'D', 'G']],
    "D": [None, ['A', 'C', 'E', 'G']],
    "E": [None, ['A', 'D', 'F', 'G']],
    "F": [None, ['A', 'B', 'E', 'G']],
    "G": [None, ['B', 'C', 'D', 'E', 'F']]
}

TEST_CUT1 = {
    "A": [None, ['B', 'C', 'D', 'E', 'F']],
    "B": [None, ['A', 'C', 'F']],
    "C": [None, ['A', 'B', 'D']],
    "D": [None, ['A', 'C', 'E']],
    "E": [None, ['A', 'D', 'F']],
    "F": [None, ['A', 'B', 'E']]
}
